# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20161018_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soliciation_number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('comments', models.TextField()),
                ('link', models.URLField()),
                ('years', models.IntegerField(default=0)),
                ('award_count', models.IntegerField(default=0)),
                ('amount_max', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deadline', models.DateTimeField()),
                ('tags', tagging.fields.TagField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to=b'logos')),
                ('website', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Project')),
            ],
        ),
        migrations.AddField(
            model_name='grant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Organization'),
        ),
    ]
