# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20161120_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='corpus',
            field=models.TextField(default=b' '),
        ),
    ]
