# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-17 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_match_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
