# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-23 03:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0016_resource_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('market_cap', models.DecimalField(decimal_places=0, default=0, max_digits=21)),
                ('chart_24h', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=21)),
                ('supply', models.DecimalField(decimal_places=0, default=0, max_digits=21)),
                ('volume_24h', models.DecimalField(decimal_places=0, default=0, max_digits=21)),
                ('percent_1h', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('percent_24h', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('percent_7d', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('donation_count', models.IntegerField(default=0)),
                ('donation_total', models.DecimalField(decimal_places=0, default=0, max_digits=21)),
                ('donation_wallet', models.TextField()),
                ('percent_locked', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('masternode_count', models.IntegerField(default=0)),
                ('masternode_cost_coins', models.DecimalField(decimal_places=0, default=0, max_digits=21)),
                ('masternode_cost_dollars', models.DecimalField(decimal_places=0, default=0, max_digits=21)),
                ('masternode_roi_days', models.IntegerField(default=0)),
                ('masternode_coins_daily', models.DecimalField(decimal_places=0, default=0, max_digits=21)),
                ('masternode_roi_yearly_percent', models.DecimalField(decimal_places=2, default=0, max_digits=21)),
                ('masternode_dollars_daily', models.DecimalField(decimal_places=0, default=0, max_digits=21)),
                ('masternode_dollars_weekly', models.DecimalField(decimal_places=0, default=0, max_digits=21)),
                ('masternode_dollars_monthly', models.DecimalField(decimal_places=0, default=0, max_digits=21)),
                ('masternode_dollars_yearly', models.DecimalField(decimal_places=0, default=0, max_digits=21)),
                ('algorithm', models.CharField(max_length=200)),
                ('block_count', models.IntegerField(default=0)),
                ('proof_type', models.CharField(max_length=200)),
                ('pool1', models.URLField(blank=True, null=True)),
                ('pool2', models.URLField(blank=True, null=True)),
                ('pool3', models.URLField(blank=True, null=True)),
                ('emoji', models.URLField(blank=True, null=True)),
                ('exchange1', models.URLField(blank=True, null=True)),
                ('exchange2', models.URLField(blank=True, null=True)),
                ('exchange3', models.URLField(blank=True, null=True)),
                ('social1', models.URLField(blank=True, null=True)),
                ('social2', models.URLField(blank=True, null=True)),
                ('social3', models.URLField(blank=True, null=True)),
                ('block_explorer', models.URLField(blank=True, null=True)),
                ('source_code', models.URLField(blank=True, null=True)),
                ('issue_count', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo_image', models.ImageField(upload_to=b'logos')),
                ('tags', tagging.fields.TagField(blank=True, max_length=255)),
                ('logo_word', models.ImageField(upload_to=b'words')),
                ('paper_wallet', models.URLField(blank=True, null=True)),
                ('white_paper', models.URLField(blank=True, null=True)),
                ('multi_wallet', models.URLField(blank=True, null=True)),
                ('mobile_wallet', models.URLField(blank=True, null=True)),
                ('related_to', models.CharField(blank=True, max_length=200, null=True)),
                ('windows_wallet', models.URLField(blank=True, null=True)),
                ('mac_wallet', models.URLField(blank=True, null=True)),
                ('linux_wallet', models.URLField(blank=True, null=True)),
                ('forum', models.URLField(blank=True, null=True)),
                ('chat', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
