# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-23 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_cryptocurrency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='user',
        ),
    ]
