# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-23 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_cryptocurrency_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='slug',
            field=models.SlugField(default=b'-', max_length=200, unique=True),
        ),
    ]
