# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-27 01:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_cryptocurrency_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='market_cap',
            new_name='market_cap_usd',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='percent_1h',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='percent_24h',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='percent_7d',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='supply',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='volume_24h',
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='available_supply',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=21),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 27, 1, 11, 43, 46000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='percent_change_1h',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='percent_change_24h',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='percent_change_7d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='price_btc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=21),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='price_usd',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=21),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='total_supply',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=21),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='volume_usd_24h',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=21),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'logos'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='logo_word',
            field=models.ImageField(blank=True, null=True, upload_to=b'words'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='percent_locked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
