# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20171126_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price_usd',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=21),
        ),
    ]
