# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-26 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20171126_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price_btc',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=21),
        ),
    ]
