# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-26 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20171126_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='max_supply',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21),
        ),
    ]
