# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-06 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20171126_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target_amount', models.DecimalField(decimal_places=9, default=0, max_digits=21)),
                ('current_amount', models.DecimalField(decimal_places=9, default=0, max_digits=21)),
                ('wallet_address', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('outcome', models.CharField(max_length=255)),
                ('contribution_count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Cryptocurrency')),
            ],
        ),
    ]
