# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-07 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20180106_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='target_cryptocurrency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_cryptocurrency', to='website.Cryptocurrency'),
        ),
    ]
