# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-07 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_goal_target_cryptocurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='block_explorer_balance_api',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='block_explorer_balance_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='block_time_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
