# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-07 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20180107_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='block_explorer_balance_in_satoshis',
            field=models.BooleanField(default=False),
        ),
    ]
