# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-07 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20180107_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='outcome',
        ),
        migrations.AddField(
            model_name='goal',
            name='result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
