# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-07 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20180107_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='issue_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='masternode_coins_daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='masternode_cost_dollars',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='masternode_dollars_daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='masternode_dollars_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='masternode_dollars_weekly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='masternode_dollars_yearly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21),
        ),
    ]
