# Generated by Django 2.0.3 on 2018-04-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20180107_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'ordering': ['-market_cap_usd']},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['status', '-number']},
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='website_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='website_screenshots'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='logo_word',
            field=models.ImageField(blank=True, null=True, upload_to='words'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='slug',
            field=models.SlugField(default='-', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='corpus',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
